import { useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowRight, CakeSlice, Check, ChevronRight, Clock3, Heart, LayoutDashboard, LogOut, Menu, Minus, Package, Pencil, Plus, Search, ShoppingBag, Sparkles, Trash2, Upload, X } from 'lucide-react';

const categories=['All cakes','Birthday','Anniversary','Wedding','Kids','Custom'];
const products=[
 {id:1,name:'Strawberry Celebration',category:'Birthday',price:2800,color:'#f8a7b8',emoji:'🍓',desc:'Vanilla sponge layered with strawberry cream.',rating:'4.9'},
 {id:2,name:'Midnight Chocolate',category:'Birthday',price:3200,color:'#5d4037',emoji:'🍫',desc:'Deep chocolate sponge with silky ganache.',rating:'4.8'},
 {id:3,name:'Butterfly Garden',category:'Kids',price:3800,color:'#d8a9d8',emoji:'🦋',desc:'A playful custom cake with handcrafted details.',rating:'5.0'},
 {id:4,name:'Rose Anniversary',category:'Anniversary',price:3500,color:'#e98493',emoji:'🌹',desc:'Soft red velvet finished with buttercream roses.',rating:'4.9'},
 {id:5,name:'Lavender Dream',category:'Wedding',price:7200,color:'#b8a1cf',emoji:'💜',desc:'Elegant layers for intimate celebrations.',rating:'4.7'},
 {id:6,name:'Your Custom Cake',category:'Custom',price:3000,color:'#f2bf91',emoji:'✨',desc:'Send your inspiration and we will make it yours.',rating:'5.0'}
];
const initialOrders=[
 {id:'VC-1048',customer:'Areeba Khan',cake:'Butterfly Garden',date:'Today, 6:00 PM',total:3800,status:'New'},
 {id:'VC-1047',customer:'Hamza Ali',cake:'Midnight Chocolate',date:'Tomorrow, 2:00 PM',total:3200,status:'Confirmed'},
 {id:'VC-1046',customer:'Maham Raza',cake:'Rose Anniversary',date:'Sep 16, 7:30 PM',total:3500,status:'Preparing'},
 {id:'VC-1045',customer:'Usman Shah',cake:'Strawberry Celebration',date:'Sep 15, 4:00 PM',total:2800,status:'Ready'}
];
const money=n=>new Intl.NumberFormat('en-PK').format(n);
const spring={type:'spring',stiffness:260,damping:22};

function Logo(){return <div className="logo"><span><CakeSlice size={21}/></span><div>Velvet Crumb<small>CAKE STUDIO</small></div></div>}
function ProductArt({product,large=false}){return <div className={'product-art '+(large?'large':'')} style={{'--cake':product.color}}><div className="orb one"/><div className="orb two"/><motion.div className="cake-emoji" whileHover={{rotate:-5,scale:1.08}} transition={spring}>{product.emoji}</motion.div><div className="plate"/></div>}

function Store({onAdmin}){
 const [category,setCategory]=useState('All cakes'); const [query,setQuery]=useState(''); const [cart,setCart]=useState([]); const [selected,setSelected]=useState(null); const [checkout,setCheckout]=useState(false); const [success,setSuccess]=useState(false); const [menu,setMenu]=useState(false);
 const shown=useMemo(()=>products.filter(p=>(category==='All cakes'||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())),[category,query]);
 const total=cart.reduce((s,p)=>s+p.price,0);
 const add=p=>{setCart(c=>[...c,p]);setSelected(null)};
 const submit=e=>{e.preventDefault();setCheckout(false);setCart([]);setSuccess(true);setTimeout(()=>setSuccess(false),4500)};
 return <div className="store">
  <header><Logo/><nav className={menu?'open':''}><a href="#cakes">Shop cakes</a><a href="#custom">Custom orders</a><a href="#about">Our story</a><button className="text-btn" onClick={onAdmin}>Admin</button></nav><div className="header-actions"><button className="icon-btn mobile" onClick={()=>setMenu(!menu)}><Menu/></button><button className="bag-btn" onClick={()=>cart.length&&setCheckout(true)}><ShoppingBag size={20}/><span>{cart.length}</span></button></div></header>
  <main>
   <section className="hero">
    <div className="hero-copy"><div className="eyebrow"><Sparkles size={16}/> Handmade in Karachi</div><h1>Little moments.<br/><em>Beautifully baked.</em></h1><p>Fresh celebration cakes handcrafted for birthdays, anniversaries and every sweet reason in between.</p><div className="hero-actions"><a className="primary" href="#cakes">Explore cakes <ArrowRight size={18}/></a><a className="secondary" href="#custom">Design my cake</a></div><div className="trust"><div><strong>500+</strong><span>cakes delivered</span></div><div><strong>4.9</strong><span>customer rating</span></div><div><strong>Fresh</strong><span>made to order</span></div></div></div>
    <motion.div className="hero-visual" initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.8}}><div className="float-note top">Made with love <Heart size={14} fill="currentColor"/></div><ProductArt product={products[0]} large/><div className="float-note bottom"><Clock3 size={16}/> Order 24h ahead</div></motion.div>
   </section>
   <section id="cakes" className="catalog">
    <div className="section-heading"><div><span>OUR COLLECTION</span><h2>Pick your favourite</h2></div><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search cakes"/></label></div>
    <div className="filters">{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div>
    <motion.div layout className="product-grid"><AnimatePresence>{shown.map(p=><motion.article layout key={p.id} className="product-card" initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.94}} whileHover={{y:-8,rotateX:2,rotateY:-2}} transition={spring}><button className="heart"><Heart size={18}/></button><ProductArt product={p}/><div className="product-info"><div className="meta"><span>{p.category}</span><span>★ {p.rating}</span></div><h3>{p.name}</h3><p>{p.desc}</p><div className="product-bottom"><div><small>Starting from</small><strong>Rs. {money(p.price)}</strong></div><button onClick={()=>setSelected(p)}><Plus size={19}/></button></div></div></motion.article>)}</AnimatePresence></motion.div>
   </section>
   <section id="custom" className="custom-section"><div><span className="eyebrow">MADE JUST FOR YOU</span><h2>Have a cake in mind?</h2><p>Share your reference picture, celebration date and ideas. Our team will contact you with the final design and price.</p><button className="primary" onClick={()=>setSelected(products[5])}>Start custom order <ChevronRight/></button></div><div className="custom-art"><span>🎂</span><i>your idea</i><b>+</b><i>our craft</i></div></section>
  </main>
  <footer><Logo/><p>Freshly baked in Karachi. Every celebration deserves something sweet.</p><div><a href="#">Instagram</a><a href="#">WhatsApp</a><button className="text-btn" onClick={onAdmin}>Admin login</button></div></footer>
  <AnimatePresence>{selected&&<motion.div className="modal-wrap" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={()=>setSelected(null)}><motion.div className="modal product-modal" initial={{y:70,scale:.95}} animate={{y:0,scale:1}} exit={{y:70,opacity:0}} onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><ProductArt product={selected}/><div><span className="eyebrow">{selected.category}</span><h2>{selected.name}</h2><p>{selected.desc}</p><label>Size / weight<select><option>1 pound</option><option>2 pounds</option><option>3 pounds</option></select></label><label>Flavour<select><option>Vanilla</option><option>Chocolate</option><option>Red velvet</option></select></label><label>Message on cake<input placeholder="e.g. Happy Birthday Sara"/></label><button className="primary wide" onClick={()=>add(selected)}>Add to order · Rs. {money(selected.price)}</button></div></motion.div></motion.div>}</AnimatePresence>
  <AnimatePresence>{checkout&&<motion.div className="modal-wrap" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.form className="modal checkout" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} onSubmit={submit}><button type="button" className="close" onClick={()=>setCheckout(false)}><X/></button><span className="eyebrow">GUEST CHECKOUT</span><h2>Complete your order</h2><div className="cart-list">{cart.map((p,i)=><div key={i}><span>{p.emoji}</span><p><strong>{p.name}</strong><small>1 pound · Vanilla</small></p><b>Rs. {money(p.price)}</b></div>)}</div><div className="form-grid"><label>Full name<input required placeholder="Your name"/></label><label>WhatsApp number<input required placeholder="03XX XXXXXXX"/></label><label className="full">Delivery address<textarea required placeholder="House, street and area"/></label><label>Delivery date<input required type="date"/></label><label>Preferred time<input required type="time"/></label><label className="full">Special instructions<textarea placeholder="Anything our baker should know?"/></label></div><div className="checkout-total"><span>Estimated total<small>Delivery calculated after confirmation</small></span><strong>Rs. {money(total)}</strong></div><button className="primary wide">Place order</button></motion.form></motion.div>}</AnimatePresence>
  <AnimatePresence>{success&&<motion.div className="toast" initial={{y:-30,opacity:0}} animate={{y:0,opacity:1}} exit={{opacity:0}}><span><Check/></span><div><strong>Order received!</strong><small>Our team will contact you shortly.</small></div></motion.div>}</AnimatePresence>
 </div>
}

function Admin({onStore}){
 const [orders,setOrders]=useState(initialOrders); const [tab,setTab]=useState('Overview'); const [login,setLogin]=useState(true); const [email,setEmail]=useState(''); const [password,setPassword]=useState('');
 const statuses=['New','Contacted','Confirmed','Preparing','Ready','Out for delivery','Delivered','Cancelled'];
 const advance=id=>setOrders(o=>o.map(x=>x.id===id?{...x,status:statuses[Math.min(statuses.indexOf(x.status)+1,6)]}:x));
 if(login)return <div className="login-page"><motion.div className="login-card" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><Logo/><span className="eyebrow">BAKERY ADMIN</span><h1>Welcome back</h1><p>Manage cakes, orders and deliveries in one place.</p><form onSubmit={e=>{e.preventDefault();setLogin(false)}}><label>Email address<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@bakery.com"/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label><button className="primary wide">Sign in <ArrowRight/></button></form><button className="text-btn back" onClick={onStore}>← Return to store</button></motion.div></div>;
 return <div className="admin"><aside><Logo/><div className="admin-nav">{['Overview','Orders','Cakes','Categories'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x==='Overview'?<LayoutDashboard/>:x==='Orders'?<Package/>:x==='Cakes'?<CakeSlice/>:<Sparkles/>}{x}{x==='Orders'&&<b>4</b>}</button>)}</div><button className="logout" onClick={()=>setLogin(true)}><LogOut/> Log out</button></aside><section className="admin-main"><div className="admin-top"><div><span>Sunday, September 14</span><h1>{tab}</h1></div><button className="primary" onClick={onStore}>View storefront <ArrowRight/></button></div>
 {tab==='Overview'&&<><div className="stats"><article><span>Orders today</span><strong>12</strong><small className="up">↑ 18% this week</small></article><article><span>Pending confirmation</span><strong>4</strong><small>Needs your attention</small></article><article><span>In preparation</span><strong>7</strong><small>2 due within 3 hours</small></article><article><span>This month</span><strong>Rs. 184k</strong><small className="up">↑ 12.4% revenue</small></article></div><div className="dashboard-grid"><div className="panel"><div className="panel-title"><div><h2>Upcoming orders</h2><p>Keep every celebration on schedule.</p></div><button onClick={()=>setTab('Orders')}>View all</button></div><OrderTable orders={orders.slice(0,4)} advance={advance}/></div><div className="panel deliveries"><div className="panel-title"><div><h2>Today’s progress</h2><p>12 orders scheduled</p></div></div>{[['Confirmed',3,25],['Preparing',5,42],['Ready',2,17],['Delivered',2,17]].map(x=><div className="progress-row" key={x[0]}><div><span>{x[0]}</span><b>{x[1]}</b></div><div><i style={{width:x[2]+'%'}}/></div></div>)}</div></div></>}
 {tab==='Orders'&&<div className="panel full-panel"><div className="panel-title"><div><h2>All orders</h2><p>Review details and update preparation progress.</p></div><label className="search"><Search/><input placeholder="Search orders"/></label></div><OrderTable orders={orders} advance={advance}/></div>}
 {tab==='Cakes'&&<div className="panel full-panel"><div className="panel-title"><div><h2>Cake collection</h2><p>Add, edit, hide or remove products and media.</p></div><button className="primary"><Plus/> Add cake</button></div><div className="admin-products">{products.map(p=><article key={p.id}><ProductArt product={p}/><div><span>{p.category}</span><h3>{p.name}</h3><strong>Rs. {money(p.price)}</strong></div><div className="row-actions"><button><Upload/></button><button><Pencil/></button><button className="danger"><Trash2/></button></div></article>)}</div></div>}
 {tab==='Categories'&&<div className="panel full-panel"><div className="panel-title"><div><h2>Categories</h2><p>Organize how customers discover cakes.</p></div><button className="primary"><Plus/> Add category</button></div><div className="category-admin">{categories.slice(1).map((x,i)=><div key={x}><span style={{background:['#f8a7b8','#e98493','#d8a9d8','#b8a1cf','#f2bf91'][i]}}>{['🎈','💞','💍','🧸','✨'][i]}</span><div><strong>{x}</strong><small>{products.filter(p=>p.category===x).length} products</small></div><button><Pencil/></button><button className="danger"><Trash2/></button></div>)}</div></div>}
 </section></div>
}
function OrderTable({orders,advance}){return <div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Cake</th><th>Delivery</th><th>Total</th><th>Status</th><th/></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><strong>{o.id}</strong></td><td>{o.customer}</td><td>{o.cake}</td><td>{o.date}</td><td>Rs. {money(o.total)}</td><td><span className={'status '+o.status.toLowerCase().replaceAll(' ','-')}>{o.status}</span></td><td><button className="next" onClick={()=>advance(o.id)} title="Move to next stage"><ChevronRight/></button></td></tr>)}</tbody></table></div>}
export default function App(){const [admin,setAdmin]=useState(location.hash==='#admin');return admin?<Admin onStore={()=>{setAdmin(false);location.hash=''}}/>:<Store onAdmin={()=>{setAdmin(true);location.hash='admin'}}/>}